import { z } from "zod";

/**
 * Canonical color families a yarn color can belong to. Deliberately a small,
 * closed set — the source vendor's own yarn line has essentially one option
 * per family (see AGENTS.md), so this is the right granularity for "do I
 * have the yarn for this," not a full color-name taxonomy.
 */
export const ColorFamily = z.enum([
  "Black",
  "White",
  "Gray",
  "Brown",
  "Tan",
  "Cream",
  "Red",
  "Pink",
  "Orange",
  "Yellow",
  "Green",
  "Blue",
  "Purple",
  "Gold",
  "Silver",
  "Other",
]);
export type ColorFamily = z.infer<typeof ColorFamily>;

export const YarnWeight = z.enum([
  "fingering",
  "medium",
  "aran",
  "bulky",
  "unknown",
]);
export type YarnWeight = z.infer<typeof YarnWeight>;

/**
 * One color requirement for a pattern, restructured from the flat text the
 * PDFs actually contain ("Blue", "Dark Brown", "Skin color") into a record
 * with match-confidence built in. See AGENTS.md's "Where this was headed."
 */
export const MaterialRow = z.object({
  colorRaw: z.string(), // original extracted text, kept for auditability
  colorFamily: ColorFamily,
  qualifier: z.string().nullable(), // e.g. "Dark", "Navy" — only ~8% of rows have one
  isPlaceholder: z.boolean(), // "Skin color" / "your choice" — not a real constraint
  weight: YarnWeight,
  amountYds: z.number().nonnegative().nullable(), // null when a yardage genuinely wasn't captured
});
export type MaterialRow = z.infer<typeof MaterialRow>;

export const SkillLevel = z.enum(["Beginner", "Beginner +", "Intermediate", "Unknown"]);
export type SkillLevel = z.infer<typeof SkillLevel>;

export const SewingAmount = z.enum(["none", "low", "medium", "high", "unknown"]);
export type SewingAmount = z.infer<typeof SewingAmount>;

/**
 * A single amigurumi pattern (the initial dataset comes from one source
 * vendor, but nothing here is vendor-specific), consolidated from the
 * tracker + extracted yarn data. `haveIt`/`completed` here are just seed
 * defaults for first load — the live source of truth after that is the
 * browser's localStorage.
 */
export const Pattern = z.object({
  id: z.string(), // slug, stable join key for localStorage user-state records
  name: z.string(),
  category: z.string(),
  subcategory: z.string().nullable(),
  collectionTags: z.array(z.string()),
  skillLevel: SkillLevel,
  sewingAmount: SewingAmount,
  materials: z.array(MaterialRow),
  haveIt: z.boolean(),
  completed: z.boolean(),
  purchaseUrl: z.string().nullable(), // link to where to buy the pattern/kit — never the pattern itself
  imageUrl: z.string().nullable(),
  tags: z.array(z.string()),
});
export type Pattern = z.infer<typeof Pattern>;

export const Catalog = z.array(Pattern);
export type Catalog = z.infer<typeof Catalog>;

/**
 * User-editable state, persisted client-side only (localStorage), keyed by
 * Pattern.id. Kept separate from Pattern/Catalog on purpose: the catalog is
 * a build artifact regenerated by the pipeline, this is the one thing the
 * app itself ever writes.
 */
export const PatternUserState = z.object({
  haveIt: z.boolean(),
  completed: z.boolean(),
  notes: z.string(),
  // Distinct from haveIt: haveIt is "I own this pattern", wantToMake is "this
  // is on my near-term to-do list". The Shopping List aggregates yardage
  // needed across wantToMake patterns, not every owned-but-unmade one --
  // otherwise it's the whole 650+ pattern collection's worth of yarn.
  wantToMake: z.boolean().default(false),
});
export type PatternUserState = z.infer<typeof PatternUserState>;

export const STASH_SCHEMA_VERSION = 1;

export const Stash = z.object({
  version: z.literal(STASH_SCHEMA_VERSION),
  onHandYdsByFamily: z.record(ColorFamily, z.number().nonnegative()),
  // "I have some red and green" without measuring yardage -- a faster path
  // than the per-family yds table for the common case of just wanting a
  // quick "what can I make" answer. Any family listed here is treated as
  // fully on-hand regardless of onHandYdsByFamily.
  quickHaveFamilies: z.array(ColorFamily).default([]),
});
export type Stash = z.infer<typeof Stash>;

export const USER_STATE_SCHEMA_VERSION = 1;

export const UserStateStore = z.object({
  version: z.literal(USER_STATE_SCHEMA_VERSION),
  patterns: z.record(z.string(), PatternUserState),
  stash: Stash,
});
export type UserStateStore = z.infer<typeof UserStateStore>;
